//package com.stockscore.stockscore_new.web.application;
//
//import com.stockscore.stockscore_new.data.entity.Stock;
//import com.stockscore.stockscore_new.data.repository.StockRepository;
//import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.stereotype.Controller;
//import org.springframework.web.bind.annotation.RequestMapping;
//import org.springframework.web.bind.annotation.RequestMethod;
//
///**
// * Created by heesukjang on 12/6/17.
// */
//
//
//
//@Controller
//@RequestMapping(value="/stock")
//public class StockController {
//
//    //    @RequestMapping(method= RequestMethod.GET)
////    public String getFavorite(@RequestParam(value="stockTicker", required=false)String ticker, Model model) {
////        List<StockFavorite> stockFavoriateList = this.favoriteService.geFavoriteForStockTicker(ticker);
////        model.addAttribute("stockFavorite", stockFavoriateList);
////        return "favorite";
////    }
//
////    @Autowired
////    private StockRepository stockRepository;
////
////    @RequestMapping(method = RequestMethod.GET)
////    public String getStock() {
////        // pull the stock that has id=2 (autogenerated) (
////        Stock stock = (Stock) stockRepository.findOne(2);
////        System.out.println("stock name: " + stock.getStockName());
////        System.out.println("stock favorires: " + stock.getFavorites().iterator().next().getStock().getStockTicker());
////        System.out.println("stock favorires: " + stock.getFavorites().iterator().next().getStock().getStockIndus());
////        System.out.println("stock shares: " + stock.getShares().iterator().next().getStock().getStockTicker());
////        return "stock";    //That string is actually going to get translated by the Thymeleaf engine into the name of a template. In our resources directory
//    }
//
//}
